export const PLACEHOLDERS = {
  TARGET: '목표를 선택해주세요',
  TITLE_TODO: '할 일의 제목을 적어주세요',
  FILE: '파일을 업로드해주세요',
  LINK_INPUT: '링크를 첨부해주세요',
  DATE_RANGE: '날짜 범위를 선택해주세요',
  NAME: '이름을 입력해주세요',
  EMAIL: '이메일을 입력해주세요',
  PASSWORD: '비밀번호를 입력해주세요',
  PASSWORD_CHECK: '비밀번호를 다시 입력해주세요',
  SEARCH: '검색어를 입력해주세요',
  CURRENT_PASSWORD: '현재 비밀번호를 입력해주세요',
  NEW_PASSWORD: '새 비밀번호를 입력해주세요',
  NEW_PASSWORD_CHK: '새 비밀번호를 다시 입력해주세요',
};
